export const siteConfig = {
  name: 'Hexallo',
  description: 'Professional Next.js application built with TypeScript and Tailwind CSS',
  url: 'https://hexallo.com',

  // Header configuration

  header: {
    // Navigation Bar 1
    topBar: {
      leftLinks: [
        { label: 'Events Calendar', href: '/events-calendar' },
        { label: 'Blog', href: '/blog' },
        { label: 'Limelight', href: '/limelight' },
      ],
      centerSelectors: [
        {
          type: 'language',
          label: 'EN(US)',
          value: 'en-us',
          icon: 'globe',
          iconPath: '/images/globe.svg',
          options: [
            { label: 'English (US)', value: 'en-us', code: 'EN(US)' },
            { label: 'English (UK)', value: 'en-gb', code: 'EN(GB)' },
            { label: 'Spanish', value: 'es', code: 'ES' },
            { label: 'French', value: 'fr', code: 'FR' },
            { label: 'German', value: 'de', code: 'DE' },
            { label: 'Italian', value: 'it', code: 'IT' },
            { label: 'Portuguese', value: 'pt', code: 'PT' },
            { label: 'Chinese', value: 'zh', code: 'ZH' },
            { label: 'Japanese', value: 'ja', code: 'JA' },
            { label: 'Korean', value: 'ko', code: 'KO' },
            { label: 'Arabic', value: 'ar', code: 'AR' },
            { label: 'Hindi', value: 'hi', code: 'HI' },
          ],
        },
        {
          type: 'country',
          label: 'United States',
          value: 'us',
          icon: 'flag',
          iconPath: '/images/Flags.svg', 
          options: [
            { label: 'United States', value: 'us', flag: '🇺🇸' },
            { label: 'Canada', value: 'ca', flag: '🇨🇦' },
            { label: 'United Kingdom', value: 'gb', flag: '🇬🇧' },
            { label: 'Australia', value: 'au', flag: '🇦🇺' },
          ],
        },
        {
          type: 'state',
          label: 'California',
          value: 'ca',
          options: [
            { label: 'California', value: 'ca' },
            { label: 'New York', value: 'ny' },
            { label: 'Texas', value: 'tx' },
            { label: 'Florida', value: 'fl' },
            { label: 'Illinois', value: 'il' },
            { label: 'Pennsylvania', value: 'pa' },
            { label: 'Ohio', value: 'oh' },
          ],
        },
      ],
      rightLinks: [
        { label: 'Sign In | Up', href: '/sign-in' },
        { label: 'Business', href: '/business', highlight: true },
        { label: 'Create Event', href: '/create-event', bold: true },
      ],
    },
    // Navigation Bar 2
    mainNav: {
      logo: {
        src: '/images/logo.svg',
        alt: 'Hexallo',
        href: '/',
      },
      links: [
        { label: 'Explore', href: '/explore', active: true },
        { label: 'Services', href: '/services' },
        { label: 'Nightlife', href: '/nightlife' },
        { label: 'Travel', href: '/travel' },
        { label: 'Accommodation', href: '/accommodation' },
        { label: 'Spaces', href: '/spaces' },
        { label: 'Subscriptions', href: '/subscriptions' },
        { label: 'Vouchers', href: '/vouchers' },
        { label: 'Rentals', href: '/rentals' },
        { label: 'Voting', href: '/voting' },
        { label: 'Shop', href: '/shop' },
        { label: 'Essentials', href: '/essentials' },
        { label: 'Healthcare', href: '/healthcare' },
        { label: 'Jobs', href: '/jobs' },
        { label: 'Marketplace', href: '/marketplace' },
      ],
    },
    // Navigation Bar 3
    subNav: {
      links: [
        { label: 'Home', href: '/', active: true },
        { label: 'Events', href: '/events' },
        { label: 'Tours', href: '/tours' },
        { label: 'Activities', href: '/activities' },
        { label: 'Indulge', href: '/indulge' },
        { label: 'Places', href: '/places' },
        { label: 'Movies', href: '/movies' },
        { label: 'Sports', href: '/sports' },
        { label: 'Restaurants', href: '/restaurants' },
        { label: 'Find a table', href: '/find-a-table' },
        { label: 'Conferences', href: '/conferences' },
        { label: 'Workshops', href: '/workshops' },
        { label: 'Auditions', href: '/auditions' },
        { label: 'People', href: '/people' },
        { label: 'World Famous', href: '/world-famous' },
        { label: 'Social Buddies', href: '/social-buddies' },
        { label: 'Virtual Experiences', href: '/virtual-experiences' },
      ],
    },
  },


  // Home configuration
  home: {
    hero: {
      title: "Discover, Book & Enjoy What's Happening Around You",
      subtitle: "From local events to world-famous experiences — all in one place.",
      searchPlaceholders: {
        event: "Search any event",
        where: "Where",
        when: "When",
      },
      backgroundImages: [
        "/images/hero-bg.jpg",
        "/images/accomodations.jpg",
        "/images/activity.png",
        "/images/destination.png",
        "/images/events.jpg",
        "/images/Exclusives-1.jpg",
      ],
    },

    spotlight: [
      {
        id: 'spotlight-1',
        image: '/images/image-card-1.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'spotlight-2',
        image: '/images/image-card-2.png',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'spotlight-3',
        image: '/images/image-card-3.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'spotlight-4',
        image: '/images/image-card-4.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
    ],

    hotThisWeek: [
      {
        id: 'hot-1',
        image: '/images/image-card-5.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'hot-2',
        image: '/images/image-card-6.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'hot-3',
        image: '/images/image-card-7.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'hot-4',
        image: '/images/image-card-8.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
    ],

    unmissable: [
      {
        id: 'unmissable-1',
        image: '/images/image-card-9.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'unmissable-2',
        image: '/images/image-card-10.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'unmissable-3',
        image: '/images/image-card-11.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'unmissable-4',
        image: '/images/image-card-12.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        href: '/events/dj-liv-north-live',
      },
    ],

    forYou: [
      {
        id: 'for-you-1',
        image: '/images/image-card-13.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'for-you-2',
        image: '/images/image-card-14.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'for-you-3',
        image: '/images/image-card-15.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'for-you-4',
        image: '/images/image-card-16.jpg',
        category: 'Lounge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
    ],

    buzzingDestinations: [
      {
        id: 'buzzing-1',
        image: '/images/buzzing-1.jpg',
        category: 'Destination',
        title: 'Washington D.C.',
        date: 'Mon, 2nd Dec',
        time: 'All Day',
        location: 'United States',
        price: 'From USD 150',
        href: '/destinations/washington-dc',
      },
      {
        id: 'buzzing-2',
        image: '/images/buzzing-2.jpg',
        category: 'Destination',
        title: 'Pisa, Italy',
        date: 'Tue, 3rd Dec',
        time: 'All Day',
        location: 'Italy',
        price: 'From USD 120',
        href: '/destinations/pisa',
      },
      {
        id: 'buzzing-3',
        image: '/images/buzzing-3.jpg',
        category: 'Destination',
        title: 'London, UK',
        date: 'Wed, 4th Dec',
        time: 'All Day',
        location: 'United Kingdom',
        price: 'From USD 180',
        href: '/destinations/london',
      },
      {
        id: 'buzzing-4',
        image: '/images/buzzing-4.jpg',
        category: 'Destination',
        title: 'Dubai, UAE',
        date: 'Thu, 5th Dec',
        time: 'All Day',
        location: 'United Arab Emirates',
        price: 'From USD 200',
        href: '/destinations/dubai',
      },
    ],

    ghanasTop10s: [
      {
        id: 'ghana-1',
        image: '/images/image-card-17.jpg',
        category: 'Event',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'ghana-2',
        image: '/images/image-card-18.jpg',
        category: 'Tour',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'ghana-3',
        image: '/images/image-card-19.jpg',
        category: 'Activity',
        title: 'DJ Liv North Live',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
      {
        id: 'ghana-4',
        image: '/images/image-card-20.jpg',
        category: 'Indulge',
        title: 'DJ Liv North Live',
        date: 'Wed, 5th Dec',
        time: '10:30 PM - 12:30 PM',
        location: 'NewYork City',
        price: 'USD 89',
        rating: 4.8,
        href: '/events/dj-liv-north-live',
      },
    ],

    exclusives: [
      {
        id: 'exclusive-1',
        image: '/images/Exclusives-1.jpg',
        title: 'Private Tours',
        description: "Your guide to the most happening events this weekend — from concerts to pop-ups.",
        ctaText: 'Explore Now',
        href: '/exclusives/private-tours',
      },
      {
        id: 'exclusive-2',
        image: '/images/Exclusives-2.jpg',
        title: 'Private Tours',
        description: "Your guide to the most happening events this weekend — from concerts to pop-ups.",
        ctaText: 'Explore Now',
        href: '/exclusives/private-tours',
      },
    ],
    hiddenGems: [
      {
        id: 'hidden-gem-1',
        image: '/images/discover-1.jpg',
        title: 'The Secret Garden Café',
        description: 'AccraHidden courtyard serving organic brunch & live music evenings.',
        ctaText: 'Explore Now',
        href: '/hidden-gems/secret-garden-cafe',
      },
      {
        id: 'hidden-gem-2',
        image: '/images/dicover-2.jpg',
        title: "Napa's Underground Jazz",
        description: 'Vintage cellar turned into an intimate live stages.',
        ctaText: 'Explore Now',
        href: '/hidden-gems/napa-underground-jazz',
      },
      {
        id: 'hidden-gem-3',
        image: '/images/discover-3.jpg',
        title: 'Sky Hammock Trail',
        description: 'BaliSwing over the valley — a serene thrill far from crowds',
        ctaText: 'Explore Now',
        href: '/hidden-gems/sky-hammock-trail',
      },
      {
        id: 'hidden-gem-4',
        image: '/images/discover.jpg',
        title: 'Sky Hammock Trail',
        description: 'BaliSwing over the valley — a serene thrill far from crowds',
        ctaText: 'Explore Now',
        href: '/hidden-gems/sky-hammock-trail',
      },
    ],
    globalHighlights: [
      {
        id: 'global-1',
        image: '/images/global-1.jpg',
        title: 'Paris',
        description: 'Culinary nights & art walks',
        ctaText: 'Explore Now',
        href: '/destinations/paris',
      },
      {
        id: 'global-2',
        image: '/images/global-2.jpg',
        title: 'Tokyo',
        description: 'Hidden rooftop bars & pop-up events',
        ctaText: 'Explore Now',
        href: '/destinations/tokyo',
      },
      {
        id: 'global-3',
        image: '/images/global-3.jpg',
        title: 'New York',
        description: 'Adventure escapes & wine tours',
        ctaText: 'Explore Now',
        href: '/destinations/new-york',
      },
      {
        id: 'global-4',
        image: '/images/global-4.jpg',
        title: 'New York',
        description: 'Adventure escapes & wine tours',
        ctaText: 'Explore Now',
        href: '/destinations/new-york',
      },
    ],

    exploreGhana: [
      {
        id: 'ghana-events',
        image: '/images/events.jpg',
        title: 'Events',
        rating: 3.5,
        href: '/explore/events',
      },
      {
        id: 'ghana-activities',
        image: '/images/activity.png',
        title: 'Activities',
        rating: 3.5,
        href: '/explore/activities',
      },
      {
        id: 'ghana-restaurants',
        image: '/images/resturants.jpg',
        title: 'Restaurants',
        rating: 3.5,
        href: '/explore/restaurants',
      },
      {
        id: 'ghana-tours',
        image: '/images/destination.png',
        title: 'Tours',
        rating: 3.5,
        href: '/explore/tours',
      },
      {
        id: 'ghana-services',
        image: '/images/services.png',
        title: 'Services',
        rating: 3.5,
        href: '/explore/services',
      },
      {
        id: 'ghana-destinations',
        image: '/images/destination.png',
        title: 'Destinations',
        rating: 3.5,
        href: '/explore/destinations',
      },
      {
        id: 'ghana-places',
        image: '/images/places.jpg',
        title: 'Places',
        rating: 3.5,
        href: '/explore/places',
      },
      {
        id: 'ghana-accommodations',
        image: '/images/accomodations.jpg',
        title: 'Accommodations',
        rating: 3.5,
        href: '/explore/accommodations',
      },
    ],

    blazingDeals: {
      title: "Blazing Deals",
      description: "Don't miss our most exciting limited-time offers and new-user specials.",
      ctaText: "Explore Offers Now",
      ctaHref: "/deals",
      countdown: {
        days: 2,
        hours: 6,
        minutes: 5,
        seconds: 30,
        endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
      },
      deals: [],
    },
  },
  
  
  // Footer configuration
  footer: {
    brand: {
      copyright: 'All rights reserved Hexallo LLC 2023',
    },
    links: [
      {
        label: 'Privacy policy',
        href: '/',
      },
      {
        label: 'Terms of service',
        href: '/',
      },
      {
        label: 'Contact us',
        href: '/',
      },
    ],
    social: [
      {
        name: 'X (Twitter)',
        href: 'https://twitter.com/',
        icon: '/icons/x.svg',
      },
      {
        name: 'LinkedIn',
        href: 'https://linkedin.com/',
        icon: '/icons/linkedin.svg',
      },
      {
        name: 'Facebook',
        href: 'https://facebook.com/',
        icon: '/icons/facebook.svg',
      },
      {
        name: 'Instagram',
        href: 'https://instagram.com/',
        icon: '/icons/instagram.svg',
      },
      {
        name: 'WhatsApp',
        href: 'https://wa.me/1234567890',
        icon: '/icons/whatsapp.svg',
      },
    ],
  },
};

